version: 2.1

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: golang:1.22.3

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}
            - go-mod-v1
      - run:
          name: Download dependencies
          command: go mod vendor
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            bad_files=$(gofmt -l . | (grep -v ^vendor/ || :))
            if [[ "${bad_files}" != "" ]]; then
              echo "Lint failed on the following files:"
              echo ${bad_files}
              exit 1
            fi

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: |
            go build -mod vendor -o ./build/ ./cmd/*

workflows:
  version: 2
  main:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
          requires:
            - setup
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
