version: 2.1

defaults: &defaults
  working_directory: /app
  docker:
    - image: cimg/go:1.22.3

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Save version
          command: git describe --tags | tee .version
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}
            - go-mod-v1
      - run:
          name: Download dependencies
          command: go mod vendor
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: |
            bad_files=$(gofmt -l . | (grep -v ^vendor/ || :))
            if [[ "${bad_files}" != "" ]]; then
              echo "Lint failed on the following files:"
              echo ${bad_files}
              exit 1
            fi

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: |
            go build -mod vendor -o ./build/ ./cmd/*

  publish:
    <<: *defaults
    docker:
      - image: gcr.io/kaniko-project/executor:v1.23.1-debug
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build and publish image
          command: |
            export VERSION=$(cat .version)
            /kaniko/executor \
              --context dir:///app \
              --dockerfile Containerfile \
              --destination ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:${VERSION}

workflows:
  version: 2
  main:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
          requires:
            - setup
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - publish:
          filters:
            tags:
              only: /.*/
          requires:
            - build
